### ISSUE TITLE
Markdown doesn't seem to like back ticks in block snippets

### ISSUE THREAD

**Issue by aturkewi** [learn-co-curriculum/skills-based-js-scope#3] opened 2016-07-01 02:01 UTC
@pletcher I'm pretty sure this is a wider Learn problem, but given that back ticks are used for string interpolation in JS, we may really want to look into this. I've noticed this in a couple of labs, but it looks particularly rough here. If you think it's worth it, Kate may be a good person to tag in here as well. 

![screen shot 2016-06-30 at 9 58 33 pm](https://cloud.githubusercontent.com/assets/13033515/16509755/122e28bc-3f0e-11e6-8174-08200d61c026.png)

**Comment by pletcher** [comment] 2016-07-01 02:01
Thanks for opening this issue!

Keep in mind that this space is for specific issues related to the content of this lesson.

If you're reporting on the content of this lesson, it'd be super helpful if you could include a stack trace of any errors that you're seeing.

If you'd like to report a bug about the Learn IDE, the Ask a Question form, opening a file, or the lights not working on Learn, please report a bug directly on https://learn.co. (You can find the bug report form by clicking on your avatar in the upper right, and then selecting "Report A Bug".)

Please be sure to include steps to reproduce (be as detailed as possible) and any relevant information about your environment. (Are you using the Learn IDE? Coding on a refurbished toaster?) We'll be sure to figure out what's going on — and to jump in and help — just as soon as we can. Thanks!

**Comment by pletcher** [comment] 2016-07-01 14:23
Yeah, this looks like a parser issue to me. cc @ktravers

**Comment by ktravers** [comment] 2016-07-03 15:47
related ticket: https://github.com/flatiron-labs/ironboard/issues/5810

**Comment by pletcher** [comment] 2016-07-06 22:23
I'm going to leave this open but remove my assignment -- we can't remove the backticks from these code blocks, but should track the related issues.

**Comment by gj** [comment] 2017-07-10 18:54
Closing because of https://github.com/flatiron-labs/ironboard/issues/9237#event-1023034354

**Closed by gj** 2017-07-10 18:54 UTC
Labels: icebox
